# Numpy 的 ndarray ：一种多维数组对象

In [1]:
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim #维度

2

In [9]:
arr2.shape

(2, 4)

In [10]:
arr1.ndim

1

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int32')

In [14]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros((10,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#  ndarray 的数据类型

In [17]:
arr1 = np.array([1,2,3],dtype=np.int32)

In [18]:
arr2 = np.array([1,2,3],dtype=np.float64)

In [19]:
arr1.dtype

dtype('int32')

In [20]:
arr2.dtype

dtype('float64')

In [21]:
arr = np.array([1,2,3,4])

In [22]:
float_arr = arr.astype(np.float64)

In [23]:
arr.dtype

dtype('int32')

In [24]:
float_arr.dtype

dtype('float64')

# 数组和标量间的运算

In [25]:
arr = np.array([[1,2,3],[4,5,6]],dtype=np.float64)

In [26]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [27]:
arr * arr #对应元素相乘

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [28]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [29]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [30]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

# 基本的索引和切片

In [31]:
arr = np.arange(10)

In [32]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[5]

5

In [34]:
arr[5:8]

array([5, 6, 7])

In [35]:
arr[5:8] = 12

In [36]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [37]:
arr_slice = arr[5:8]

In [38]:
arr_slice[:] = 64

In [39]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [40]:
# 大数据处理 复制会引起性能问题

In [41]:
arr2d = np.arange(9)

In [42]:
arr2d = arr2d.reshape((3,3))

In [43]:
arr2d[:2,2:]

array([[2],
       [5]])

# 布尔型索引

In [44]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [45]:
data = np.random.randn(7,4)

In [46]:
data

array([[-0.00185371,  1.581834  , -1.59639577, -1.21947918],
       [ 0.80140387, -0.33403666,  0.05451868, -1.33662992],
       [-0.30194986,  0.54237255,  1.38055756, -0.14978716],
       [-0.7900743 ,  0.33848608, -0.56910351,  0.40485026],
       [-0.36020895,  0.13622851, -0.12359129,  1.51250845],
       [ 0.21002533, -1.43698899, -1.14135337,  1.26840291],
       [ 0.99283966,  0.06124208, -0.05947825, -0.53655621]])

In [47]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [48]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [49]:
data[names == 'Bob']

array([[-0.00185371,  1.581834  , -1.59639577, -1.21947918],
       [-0.7900743 ,  0.33848608, -0.56910351,  0.40485026]])

In [50]:
data[names == 'Bob',2:]

array([[-1.59639577, -1.21947918],
       [-0.56910351,  0.40485026]])

In [51]:
data[names == 'Bob',3]

array([-1.21947918,  0.40485026])

In [52]:
mask = (names == 'Bob') | (names == 'Will')

In [53]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [54]:
data[mask]

array([[-0.00185371,  1.581834  , -1.59639577, -1.21947918],
       [-0.30194986,  0.54237255,  1.38055756, -0.14978716],
       [-0.7900743 ,  0.33848608, -0.56910351,  0.40485026],
       [-0.36020895,  0.13622851, -0.12359129,  1.51250845]])

In [55]:
data[data < 0] = 0

In [56]:
data

array([[ 0.        ,  1.581834  ,  0.        ,  0.        ],
       [ 0.80140387,  0.        ,  0.05451868,  0.        ],
       [ 0.        ,  0.54237255,  1.38055756,  0.        ],
       [ 0.        ,  0.33848608,  0.        ,  0.40485026],
       [ 0.        ,  0.13622851,  0.        ,  1.51250845],
       [ 0.21002533,  0.        ,  0.        ,  1.26840291],
       [ 0.99283966,  0.06124208,  0.        ,  0.        ]])

# 花式索引

In [57]:
arr = np.empty((8,4))

In [58]:
arr

array([[              nan,   6.01328721e-154,   2.25293935e-321,
          1.97626258e-323],
       [  4.42682819e-321,   3.33907526e-028,   4.32801506e-321,
          1.69811485e+199],
       [  2.39127773e-321,   1.04918226e-142,   2.47032823e-321,
          6.36540300e-013],
       [  4.46635344e-321,   1.23696102e+214,   2.25293935e-321,
          1.82491638e-312],
       [  2.25293935e-321,   1.34497462e-284,   5.62949960e+014,
          1.02809038e-312],
       [  3.42308746e-210,   3.06028293e-308,   2.49259880e-306,
          1.94165661e-292],
       [  4.59988455e-287,   4.22971826e-307,   1.62597725e-260,
          6.01347002e-154],
       [  5.28964691e+180,   6.01347002e-154,   4.47593816e-091,
          5.98149672e-154]])

In [59]:
for i in range(8):
    arr[i] = i

In [60]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [61]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [62]:
arr = np.arange(64).reshape((8,8))

In [63]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [64]:
arr[[1,2,3,4],[2,3,4,5]]

array([10, 19, 28, 37])

# 数组的转置和轴的对换

In [65]:
arr = np.arange(15).reshape((3,5))

In [66]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [68]:
arr = np.arange(18).reshape((6,3))

In [69]:
np.dot(arr.T,arr) # 求内积

array([[495, 540, 585],
       [540, 591, 642],
       [585, 642, 699]])

# 通用函数：快速地元素级数函数

In [70]:
arr = np.arange(10)

In [71]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [72]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [73]:
x = np.random.randn(8)

In [74]:
x

array([-1.09842629,  0.55006067, -0.06199321, -0.04374525, -0.95453729,
        0.56641654,  0.81112579, -0.77490797])

In [75]:
y = np.random.randn(8)

In [76]:
y

array([ 0.17120908, -0.59665501, -0.59998138, -0.02909292, -0.61067712,
       -0.20118754,  0.35982901,  1.06855233])

In [78]:
np.maximum(x,y) #两个中的最大值

array([ 0.17120908,  0.55006067, -0.06199321, -0.02909292, -0.61067712,
        0.56641654,  0.81112579,  1.06855233])

In [79]:
arr = np.random.randn(8) * 5

In [80]:
np.modf(arr)

(array([-0.03590858,  0.06388202,  0.51755576,  0.89118616,  0.02872904,
         0.96258427, -0.72532433, -0.02122045]),
 array([-1.,  3.,  4.,  0.,  3.,  3., -1., -5.]))

In [81]:
arr

array([-1.03590858,  3.06388202,  4.51755576,  0.89118616,  3.02872904,
        3.96258427, -1.72532433, -5.02122045])

# 利用数组进行元素处理

In [82]:
points = np.arange(-5,5,0.01)

In [83]:
points

array([ -5.00000000e+00,  -4.99000000e+00,  -4.98000000e+00,
        -4.97000000e+00,  -4.96000000e+00,  -4.95000000e+00,
        -4.94000000e+00,  -4.93000000e+00,  -4.92000000e+00,
        -4.91000000e+00,  -4.90000000e+00,  -4.89000000e+00,
        -4.88000000e+00,  -4.87000000e+00,  -4.86000000e+00,
        -4.85000000e+00,  -4.84000000e+00,  -4.83000000e+00,
        -4.82000000e+00,  -4.81000000e+00,  -4.80000000e+00,
        -4.79000000e+00,  -4.78000000e+00,  -4.77000000e+00,
        -4.76000000e+00,  -4.75000000e+00,  -4.74000000e+00,
        -4.73000000e+00,  -4.72000000e+00,  -4.71000000e+00,
        -4.70000000e+00,  -4.69000000e+00,  -4.68000000e+00,
        -4.67000000e+00,  -4.66000000e+00,  -4.65000000e+00,
        -4.64000000e+00,  -4.63000000e+00,  -4.62000000e+00,
        -4.61000000e+00,  -4.60000000e+00,  -4.59000000e+00,
        -4.58000000e+00,  -4.57000000e+00,  -4.56000000e+00,
        -4.55000000e+00,  -4.54000000e+00,  -4.53000000e+00,
        -4.52000000e+00,

In [89]:
xs,ys = np.meshgrid(points,points)

In [85]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [90]:
import matplotlib.pyplot as plt

In [91]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [92]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

## 讲条件逻辑表述为数组运算

In [103]:
xarr = np.arange(1.1,1.6,0.1)

In [115]:
xarr

array([ 1.1,  1.2,  1.3,  1.4,  1.5])

In [98]:
yarr = np.arange(2.1,2.6,0.1)

In [99]:
cond = np.array([True,False,True,True,False])

In [100]:
result = [(x if z else y) for x ,y,z in zip(xarr,yarr,cond)]

In [101]:
result

[1.0,
 2.2000000000000002,
 1.2000000000000002,
 1.3000000000000003,
 2.5000000000000004]

In [108]:
result = np.where(cond, xarr ,yarr) # if 条件 x  else y

In [106]:
from numpy.random import randn

In [107]:
arr = randn(4,4)

In [109]:
arr

array([[-1.57788755, -1.53509158,  0.27502578, -0.14697595],
       [-0.48854508,  1.61733145, -1.31349841, -1.13075506],
       [-0.4891524 ,  1.62390438,  0.78002941,  0.20263587],
       [-0.4525481 , -0.70837403, -0.50001312, -2.12241708]])

In [110]:
np.where(arr > 0 , 2, -2)

array([[-2, -2,  2, -2],
       [-2,  2, -2, -2],
       [-2,  2,  2,  2],
       [-2, -2, -2, -2]])

In [111]:
np.where(arr >0,2,arr)

array([[-1.57788755, -1.53509158,  2.        , -0.14697595],
       [-0.48854508,  2.        , -1.31349841, -1.13075506],
       [-0.4891524 ,  2.        ,  2.        ,  2.        ],
       [-0.4525481 , -0.70837403, -0.50001312, -2.12241708]])

In [120]:
cond2 = cond.copy()

In [121]:
cond1 = cond.copy()

In [122]:
result = []
for i in range(5):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [123]:
result

[0, 3, 0, 0, 3]

In [124]:
np.where(cond1 & cond2,0,np.where(cond1,1,np.where(cond2,2,3)))

array([0, 3, 0, 0, 3])

## 数学和统计方法

In [126]:
arr = randn(5,4)

In [127]:
arr.mean()

0.047202240093186139

In [128]:
np.mean(arr)

0.047202240093186139

In [129]:
arr.sum()

0.94404480186372275

In [130]:
arr

array([[ 0.46421673, -0.33037273, -1.75371776,  1.32617247],
       [ 0.65520187, -0.80125453, -0.09384027,  1.7398653 ],
       [-1.52155153,  0.70154654,  0.07338704,  0.16798069],
       [-0.57231606, -0.38379975,  1.09042294, -0.02502636],
       [ 0.36634503, -0.13364769, -0.63501584,  0.60944871]])

In [131]:
arr.sum(0)

array([-0.60810397, -0.94752816, -1.31876389,  3.81844082])

In [132]:
arr.sum(1)

array([-0.29370128,  1.49997237, -0.57863726,  0.10928077,  0.2071302 ])

In [133]:
arr = np.arange(9).reshape(3,3)

In [134]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 用于布尔型数组的方法

In [135]:
arr = randn(100)

In [137]:
(arr > 0 ).sum()

55

In [138]:
bools = np.array([False,True,True,False])

In [139]:
bools.any()

True

In [140]:
bools.all()

False

## 排序

In [141]:
arr = randn(8)

In [142]:
arr

array([-1.75662136,  1.83944292, -0.32323673,  1.16566411,  0.8661405 ,
        1.51519225,  0.48057063,  0.95482889])

In [143]:
arr.sort()

In [144]:
arr

array([-1.75662136, -0.32323673,  0.48057063,  0.8661405 ,  0.95482889,
        1.16566411,  1.51519225,  1.83944292])

In [145]:
arr = randn(5,3)

In [147]:
arr.sort()

## 唯一化以及其他的合集逻辑

In [148]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [149]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

In [150]:
values = np.array([6,0,0,3,2,5,6])

In [151]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

# 用于数组的文件输入

## 将数组以二进制格式保存到磁盘

In [154]:
arr = np.arange(10)

In [155]:
np.save('ssome_array',arr)

In [156]:
np.load('ssome_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
np.savez('array_archive.pnz',a = arr,b = arr)

In [161]:
arch = np.load('array_archive.pnz.npz')

In [162]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 存储文件

In [163]:
#!cat array_ex.txt

'cat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [164]:
arr = np.loadtxt('array_ex.txt',delimiter=',')

In [165]:
arr

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

# 线性代数

In [166]:
x = np.array([[1,2,3],[4,5,6]],dtype=np.float64)

In [167]:
y = np.array([[6,23],[-1,7],[8,9]],dtype=np.float64)

In [168]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [169]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [170]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [171]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [172]:
np.ones(3)

array([ 1.,  1.,  1.])

In [173]:
from numpy.linalg import inv,qr

In [174]:
X = randn(5,5)

In [175]:
mat = X.T.dot(X)

In [176]:
inv(mat)

array([[ 0.40951638, -0.49537541,  0.13173419,  0.07482858,  0.07395609],
       [-0.49537541,  1.40474043, -0.08305087, -0.24226797,  0.15983655],
       [ 0.13173419, -0.08305087,  0.41706943, -0.1322112 ,  0.11532191],
       [ 0.07482858, -0.24226797, -0.1322112 ,  0.30186499, -0.11538307],
       [ 0.07395609,  0.15983655,  0.11532191, -0.11538307,  0.24990437]])

In [177]:
mat

array([[ 6.80942711,  2.48964424, -1.11204027, -1.65105635, -3.85665959],
       [ 2.48964424,  1.85565254,  0.18036861,  0.22348467, -1.90368641],
       [-1.11204027,  0.18036861,  3.49788148,  1.72083412, -0.60589015],
       [-1.65105635,  0.22348467,  1.72083412,  5.4445179 ,  2.06534999],
       [-3.85665959, -1.90368641, -0.60589015,  2.06534999,  7.59362864]])

# 随机数生成

In [178]:
sampels = np.random.normal(size=(4,4))

In [180]:
sampels

array([[ 0.23299841,  0.05612284,  1.00562907, -1.1046039 ],
       [-1.32197618,  0.75013351, -1.23523727, -0.31759014],
       [-1.54768115,  1.25956682, -1.99316428,  0.05956365],
       [-1.4047862 ,  0.37504197, -0.02113257, -0.34425875]])