# Numpy 的 ndarray ：一种多维数组对象

In [1]:
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim #维度

2

In [9]:
arr2.shape

(2, 4)

In [10]:
arr1.ndim

1

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int32')

In [14]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros((10,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#  ndarray 的数据类型

In [17]:
arr1 = np.array([1,2,3],dtype=np.int32)

In [18]:
arr2 = np.array([1,2,3],dtype=np.float64)

In [19]:
arr1.dtype

dtype('int32')

In [20]:
arr2.dtype

dtype('float64')

In [21]:
arr = np.array([1,2,3,4])

In [22]:
float_arr = arr.astype(np.float64)

In [23]:
arr.dtype

dtype('int32')

In [24]:
float_arr.dtype

dtype('float64')

# 数组和标量间的运算

In [25]:
arr = np.array([[1,2,3],[4,5,6]],dtype=np.float64)

In [26]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [27]:
arr * arr #对应元素相乘

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [28]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [29]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [30]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

# 基本的索引和切片

In [31]:
arr = np.arange(10)

In [32]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[5]

5

In [34]:
arr[5:8]

array([5, 6, 7])

In [35]:
arr[5:8] = 12

In [36]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [37]:
arr_slice = arr[5:8]

In [38]:
arr_slice[:] = 64

In [39]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [40]:
# 大数据处理 复制会引起性能问题

In [41]:
arr2d = np.arange(9)

In [42]:
arr2d = arr2d.reshape((3,3))

In [43]:
arr2d[:2,2:]

array([[2],
       [5]])

# 布尔型索引

In [44]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [45]:
data = np.random.randn(7,4)

In [46]:
data

array([[ 0.41025492, -0.00452454,  1.24800734,  0.367274  ],
       [ 0.10057253, -1.36017388, -0.38889344, -1.21437622],
       [ 0.87787215,  0.43188082, -2.03178052,  0.94621579],
       [ 0.01027114,  0.3645242 ,  1.24712952,  0.39023245],
       [-1.14308589, -0.24331309,  0.47078962,  0.17082935],
       [ 0.45462023, -1.58779624,  1.39806118,  0.74364066],
       [ 0.86293956, -0.88726306, -0.05802649, -0.08399794]])

In [47]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [48]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [49]:
data[names == 'Bob']

array([[ 0.41025492, -0.00452454,  1.24800734,  0.367274  ],
       [ 0.01027114,  0.3645242 ,  1.24712952,  0.39023245]])

In [50]:
data[names == 'Bob',2:]

array([[ 1.24800734,  0.367274  ],
       [ 1.24712952,  0.39023245]])

In [51]:
data[names == 'Bob',3]

array([ 0.367274  ,  0.39023245])

In [52]:
mask = (names == 'Bob') | (names == 'Will')

In [53]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [54]:
data[mask]

array([[ 0.41025492, -0.00452454,  1.24800734,  0.367274  ],
       [ 0.87787215,  0.43188082, -2.03178052,  0.94621579],
       [ 0.01027114,  0.3645242 ,  1.24712952,  0.39023245],
       [-1.14308589, -0.24331309,  0.47078962,  0.17082935]])

In [55]:
data[data < 0] = 0

In [56]:
data

array([[ 0.41025492,  0.        ,  1.24800734,  0.367274  ],
       [ 0.10057253,  0.        ,  0.        ,  0.        ],
       [ 0.87787215,  0.43188082,  0.        ,  0.94621579],
       [ 0.01027114,  0.3645242 ,  1.24712952,  0.39023245],
       [ 0.        ,  0.        ,  0.47078962,  0.17082935],
       [ 0.45462023,  0.        ,  1.39806118,  0.74364066],
       [ 0.86293956,  0.        ,  0.        ,  0.        ]])

# 花式索引

In [57]:
arr = np.empty((8,4))

In [58]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [59]:
for i in range(8):
    arr[i] = i

In [60]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [61]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [62]:
arr = np.arange(64).reshape((8,8))

In [63]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [64]:
arr[[1,2,3,4],[2,3,4,5]]

array([10, 19, 28, 37])

# 数组的转置和轴的对换

In [65]:
arr = np.arange(15).reshape((3,5))

In [66]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [68]:
arr = np.arange(18).reshape((6,3))

In [69]:
np.dot(arr.T,arr) # 求内积

array([[495, 540, 585],
       [540, 591, 642],
       [585, 642, 699]])